apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: db:5432
    user: root
    isDefault: true
    editable: false

    secureJsonData:
      password: root

    jsonData:
      database: centraDB   
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
